### ISSUE TITLE
Filter notes by country

### ISSUE THREAD

**Issue by arrival-spring** [ENT8R/NotesReview#100]
It would be helpful to be able to filter notes by a certain country or countries.

Notes in the list show which country they are in, so clearly this information exists.

**Comment by ENT8R** [comment]
The frontend derives the country information from the position of the note, but the search happens in the backend, where the information about the country of the note is also only implicitly defined by the position.
It would certainly be technically possible to add an additional option, but since it is already possible to restrict the search area to the visible map section, I am not sure if it is really worth adding a selection option for the country.
Can you maybe specify your use case or why you think this feature would be useful in general?

**Comment by arrival-spring** [comment]
I have knowledge of conventions and mapping practices in my country, but not so much in neighbouring countries. Therefore there are many notes that I am able to resolve from a distance (e.g. StreetComplete notes amongst others)., but I wouldn't want to do this for notes in other countries.

I can't make it so that all of my country and only my country is visible in the view.

**Comment by ppete2** [comment]
I also support this idea, for the reasons @arrival-spring mentioned. If this is not possible (yet), an alternative would be to draw a rectangle or even a polygone to selcect the area of interest. Right now "restrict the search area to the visible map section" could be a lot larger than the area of interest and if we zoom in one step we are not able anymore to see the complete area.

**Comment by ENT8R** [comment]
I finally found some time to implement another option to restrict the search to countries or arbitrary user-defined polygons. It is now possible to apply all options to certain areas, allowing searches on a more granular level (e.g. only in a certain city):

| Select countries by clicking on them | Draw custom areas |
|---|---|
| ![Screenshot 2023-11-26 at 17-36-07 NotesReview](https://github.com/ENT8R/NotesReview/assets/25306497/53bf8baa-99e9-427e-a201-0e0aa5c60447) | ![Screenshot 2023-11-26 at 17-36-53 NotesReview](https://github.com/ENT8R/NotesReview/assets/25306497/45ce34e1-a261-42a1-8520-54c9ad5c4d25) |
