### ISSUE TITLE
Allow fully removing location marker

### ISSUE THREAD

**Issue by danieldegroot2** [ENT8R/NotesReview#103]
Allow fully removing the marker which appears on location search, ie. when clicking on the map view. Once the proper location is found, it is redundant to know where it is. Currently, only the address display can be hidden.

**Comment by ENT8R** [comment]
I have now completely removed the marker and popup when searching for a location, somehow it actually did not add any value. It was just enabled by default and that is why I actually never thought about it, although it seems relatively unnecessary since the information is also (supposed to be) visible on the map itself...
