### ISSUE TITLE
enable Dependabot?

### ISSUE THREAD

**Issue by Strubbl** [ENT8R/NotesReview#109]
I just installed the dev version of notes review. It is listing 5 security vulnerabilities. Maybe it makes sense to enable dependabot for this repository?
See https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by ENT8R** [comment]
I am not a really huge fan of dependabot since Github already notifies me about possible vulnerabilities of dependencies, I think introducing dependabot will not cause the dependencies to be updated faster than they currently are (if I stay with my manual process of updating dependencies when necessary), since I would still have to (or rather want to) manually check each pull request for possible side effects.
But let me assure you that I do receive the security notifications and take a quick look at them, currently however 4 out of the 5 listed notifications are only those that affect dev dependencies, so the amount of users affected is relatively small (probably I am the only person affected by it right now...)

**Comment by Strubbl** [comment]
Thanks for clarifying.
