### ISSUE TITLE
Unknown User error when filtering dates

### ISSUE THREAD

**Issue by danieldegroot2** [ENT8R/NotesReview#113]
Viewing around Wroclaw, Poland and filtering notes to the month of March 2023 (all users, 1-31 March, only selected area) causes registered users' names to be displayed as Unknown User. This may be [due to a note causing a javascript error](https://github.com/openstreetmap/openstreetmap-website/issues/3996#issuecomment-1493074300)?

**Comment by maro-21** [comment]
Where can you see that error?

**Comment by ENT8R** [comment]
The problem is likely that a user commented on some note in the area and after that they deleted their account. If the user details are then requested via the API by NotesReview, this leads to an error and no details of any user can be shown.
I already noticed this bug a few months ago, but did not take any action yet, as I am not quite sure whether this requires a change on my side or a fix of the OpenStreetMap API.

Basically the problem is the following:
Requesting the details of the users with the ids `18597840` **and** `185978900` [fails with a 404](https://www.openstreetmap.org/api/0.6/users?users=18597840,185978900) whereas limiting the query to user `18597840` returns the [correct result](https://www.openstreetmap.org/api/0.6/users?users=18597840) because user `185978900` commented on a note and deleted their account afterwards.

**Comment by danieldegroot2** [comment]
Ok, then we wait until https://github.com/openstreetmap/openstreetmap-website/issues/2146 / https://github.com/openstreetmap/openstreetmap-website/issues/3831 / related PRs gets out of its current stall, or until @gravitystorm or someone else is able to give a hint.

**Comment by ENT8R** [comment]
This has been fixed for about two months now (requesting the user details of a deleted user does no longer fail, instead an empty response is returned by the API)

**Comment by danieldegroot2** [comment]
Ref https://github.com/openstreetmap/openstreetmap-website/pull/4190

Related issues/PRs are still open.
See also https://github.com/osmfoundation/ewg_bidding/pull/9
