### ISSUE TITLE
the colour of the notes is confusing for me

### ISSUE THREAD

**Issue by vinber** [ENT8R/NotesReview#114]
On osm.org, an open note is red, and when it's resolved" it's green

In NotesReview, it's the "opposite", a little bit confusing, specially for newer.

What's the reason for this ?

**Comment by ENT8R** [comment]
I agree that it might seem a little bit confusing at first, but let me elaborate a little bit:

In my opinion, the color red conveys that a certain action should not be pursued further, because red generally stands for a danger or some warning. In this case, the warning is not to click on notes with a red marker, as they are already marked as resolved, and thus no further action would be necessary on the part of the NotesReview user.
The color green, on the other hand, gives the impression that an action is necessary, in this case leaving a comment or changing something on the map.

One can certainly easily find arguments for the color choice of OSM (which is more focused on browsing notes instead of finding and resolving), however, the decision for or against a color is rather a philosophical one in this case I guess.
Since I initially developed NotesReview with the intention of creating a tool that provides an efficient workflow for **resolving notes**, the choice of this color combination makes sense insofar as it guides the user to primarily focus on resolving open (i.e. green) notes.

Does this answer your question?

**Comment by vinber** [comment]
yes, it's an answer but i'm not convince :D

when you're on notereviews, on a green note for example, you can open with iD, JOSM, and you're "note" are red ...

i really understand your argue but i think it's contre-intuitive with all others tools and it's a "friction" for use of NoteReviews (my issue is because i really like NoteReviews and i hope to reduce frictions :D)

**Comment by ENT8R** [comment]
I understand that it might be a little bit confusing but you still have to keep in mind that NotesReview and the main OpenStreetMap website are two different tools that both satisfy different purposes. NotesReview is much better suited for finding and especially resolving many notes and as I already said above, for me green always denotes a possibility to interact with something (see e.g. Github Issues which also use the color green when issues are still open and further action is required or even when looking at the analog world: traffic lights are also an example where the colors red and green are used the same way as in NotesReview).

The notes displayed on OSM also convey their current status in two ways (by using both colors and an icon), and I guess when used together with these icons the choice of color makes perfect sense, since the checkmark always connotes a positive action. But NotesReview uses only color coding and is not bound to the meaning of additional icons.

**Comment by vinber** [comment]
> traffic lights are also an example where the colors red and green are used the same way as in NotesReview).

red you need to stop as for a note you need to stop on it :) you can interprate color with lot of different way, it's cultural

it's of course what you decide and you prefer a different way than on osm website and several editors (and it's what i think a "mistake"

> I understand that it might be a little bit confusing but you still have to keep in mind that NotesReview and the main OpenStreetMap website are two different tools that both satisfy different purposes.

yes, i know it but it's not only main osm website but also id, josm, sc, osmand, noteheatmap, osm note de neis, ... in all this site, red is a open note and need to focus on it 

Thanks for your work on notes review

**Comment by ENT8R** [comment]
Mmh, while rereading this thread I'm not quite sure whether you mean the color of the notes when searching for **all notes** or for **open notes only**. As the behavior differs a little bit and I always assumed that you meant the color of the notes when searching for all notes, is that assumption correct? Because you actually never mentioned it before and now I'm a little bit confused whether I really understood your request.

**Comment by vinber** [comment]
An example for "all notes "
* on notes review ![image](https://github.com/ENT8R/NotesReview/assets/890869/cc8ce06e-3f72-43eb-ab4f-e76406a9772d)
* on osm 
![image](https://github.com/ENT8R/NotesReview/assets/890869/5a078f63-10f9-475f-b681-d0fe4da9851d)
* on iD 
![image](https://github.com/ENT8R/NotesReview/assets/890869/c3afee69-8433-4194-a140-e5db40eb35d4)
* on josm 
![image](https://github.com/ENT8R/NotesReview/assets/890869/85c6acfa-5842-4d27-8cc5-e162a0f0422b)
