### ISSUE TITLE
Redacted notes keep on showing

### ISSUE THREAD

**Issue by MikiDi** [ENT8R/NotesReview#120]
Notes that have been [redacted](https://wiki.openstreetmap.org/wiki/Notes#Reporting_notes), such as [#4050630](https://ent8r.github.io/NotesReview/?view=map&bbox=4.4140%2C50.8493%2C4.4552%2C50.8556&area=view&limit=48&status=all&after=2023-11-01), keep on showing on the NotesReview map as "open". I'd expect them to be categorized as "closed", or something else.

**Comment by ENT8R** [comment]
Invisible/redacted notes should (in theory) not appear in the results. The backend has a script which deletes all notes from the database which do not appear in the daily notes dump anymore. Since this is a potentially destructive operation the script needs to be executed manually every now and then so I can check for possible errors. I would like to abstain from automating this process and rather keep doing this manually. I just ran the script right now, so the note should no longer be included in the results.
The amount of invisible notes that were still visible in NotesReview is also arguably small, so feel lucky to have found such a rare note ;) (Out of nearly 4 million notes only 2300 notes should not have been visible)
