### ISSUE TITLE
Certain searches are not working

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/NotesReview#123]
See https://ent8r.github.io/NotesReview/?view=list&query=%22https%3A%2F%2Fwiki.openstreetmap.org%2Fwiki%2FTag%3Ashop%25253Dstorage_rental%22&after=2024-01-06&sort=created_at%3Aascending

It should find at least https://www.openstreetmap.org/note/4061157 and https://www.openstreetmap.org/note/4061143 and https://www.openstreetmap.org/note/4061145 and some other but is finding nothing

Not sure what is going wrong

**Comment by ENT8R** [comment]
The issue seems to be that the query is quite complex, especially searching for longer words like an URL combined with some more options takes more than the timeout of one minute to complete. There are only a few things I could do that come to my mind to improve the speed of queries. One of these things could be adding an additional option that returns the results unordered, because without sorting the results I get nearly an instant response (not possible with the current UI and API). This definitely needs some more testing, maybe some more adaptions to the text search will be necessary.

**Comment by ENT8R** [comment]
It turns out that speeding up certain (complex) queries is currently not possible due to hardware constraints of the backend server. But you are right, to inform the user about a timeout is actually a good idea, added this now with https://github.com/ENT8R/NotesReview/commit/a40fcb436bc96339d2989b78a70f32cfa6991c2d
<img width="200px" src="https://github.com/ENT8R/NotesReview/assets/25306497/1bf5ad3a-d371-4b3a-b917-de4c55318ad8">
