### ISSUE TITLE
Predefined shapes for countries

### ISSUE THREAD

**Issue by opk12** [ENT8R/NotesReview#125]
The custom area selection mechanism (introduced in #100 to generalize the feature request to filter by country) could become more user-friendly with a way to prefill the shape for the country of interest.

For example, in the geometry editor, click inside a country, to auto-select the borders. Another example (less convenient IMO): type the name in a text field to search-as-you-type, then press Enter or click in a popup list of countries.

This feature request is in the context of making a URL to be shared among the Italian community. Italy is tall and narrow, so filtering for the current view is not effective. Depending on the screen size, there are more land and notes in the view from neighboring countries than from Italy.

**Comment by ENT8R** [comment]
I am not sure if I understand your request correctly, but I guess what you want is already implemented.
Note that the area selection dialog says "Select countries by clicking on them or draw a custom shape using the toolbar on the left":
![screenrecording](https://github.com/ENT8R/NotesReview/assets/25306497/8bcb9bb5-cd15-441e-994e-b6e79c0e1435)

All areas selected this way are actually included in the URL to be shared (because a simple id depending on the areas/countries selected is appended) while custom drawn areas are not included because they can be arbitrary complex and thus leading to an URL that is not really readable anymore and consists of a (really) huge chunk of URL-encoded GeoJSON.
Maybe I will come up with a solution in the other issue, otherwise it might be better to include a warning in the sharing dialog that (complex) geometries can not be shared via an URL yet.

**Comment by opk12** [comment]
That's it! Sorry.
