### ISSUE TITLE
Notes not found when Italy is selected

### ISSUE THREAD

**Issue by opk12** [ENT8R/NotesReview#126]
The website does not find notes, if Italy is selected as the `Custom area` with a mouse click.

To reproduce, open `Filter` - `Custom area`, click on Italy, click `Close` and `Search`.

It does find notes in Italy, if
- a second State is also selected,
- or a custom geometry is used (that crosses borders or not).

Temporary workaround for the other mappers landing here: select San Marino or Vatican City.

**Comment by ENT8R** [comment]
The problem was that the simplification algorithm for country boundaries was a little bit too aggressive which effectively lead to the removal of borders of microstates like Vatican City and this resulted in an error on the backend.
I changed the algorithm, so that boundaries that are about to be removed are still preserved correctly.
