### ISSUE TITLE
Phrase in open note not found

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/NotesReview#130]
https://ent8r.github.io/NotesReview/?view=list&query=%22kindly%20revert%22&sort=created_at%3Aascending

I would expect it to find at least https://www.openstreetmap.org/note/2157842

It found nothing

**Comment by ENT8R** [comment]
Is there a reason why you enclosed the query in quotation marks? Searching for `kindly revert` instead of `"kindly revert"` lists notes containing this phrase

**Comment by matkoniecz** [comment]
I assumed that `kindly revert` will find cases where either `kindly` or `revert` are present.

I remembered it happening but I was wrong.

**Comment by ENT8R** [comment]
Ah, I see. Some time ago it was only possible to search for a combination of words by enclosing *each* of them in quotation marks (i.e. `kindly revert` would include notes either containing `kindly` OR `revert` while `"kindly" "revert"` would include notes containing `kindly` AND `revert`), see https://github.com/ENT8R/NotesReview/issues/78#issuecomment-916386000.
This behavior was a little bit strange so it has been changed and the query only works for exact phrases that appear like that in the note text, though this will likely change again in the future since this way of searching is a little bit more restrictive than before.

**Comment by matkoniecz** [comment]
> Some time ago it was only possible to search for a combination of words by enclosing each of them in quotation marks

Oh, so my memory was outdated rather than just completely confused. Nice to know :)
