### ISSUE TITLE
Show the normal OSM background.

### ISSUE THREAD

**Issue by filipca** [ENT8R/NotesReview#132]
Now the background is very light, the placenames and streets are hard to see.
Or am I missing something ?

Thanks for Notesreview, I use it a lot to go on a tour to photograph AEDs.
I copy the map with the Snipping Tool, I print it and write text balloons by hand with the content of the notes.
And to make the notes, I use Overpass.

**Comment by ENT8R** [comment]
The map that is displayed is the same since the beginning, I also did a quick comparison to see whether the provider changed anything in that regard but that does also not seem to be the case. So I do not know if I understand you correctly, but if the map and the interface in general feels too bright, you might as well try to change the theme to dark, maybe this helps a little bit:
![output](https://github.com/ENT8R/NotesReview/assets/25306497/9ecfe209-6c27-44e4-a8a4-24c3b6aa491c)
