### ISSUE TITLE
Result shows closed notes although this should be filtered out

### ISSUE THREAD

**Issue by jmizv** [ENT8R/NotesReview#136]
I have this setting (sorry it's in German)

![grafik](https://github.com/user-attachments/assets/e3b94b7e-700c-4efe-8993-60b1bafc88e8)

I'm looking in an area around Leipzig (Germany).

I closed some notes yesterday but since today some of these closed notes are showing up in my current query.
Some notes I have closed today are not showing up.

So this note is showing up although closed yesterday: https://www.openstreetmap.org/note/4370222
This note was closed today but is not showing up anymore: https://www.openstreetmap.org/note/4508404

Not sure what the problem is but it looks like it only happens for notes closed yesterday.

**Comment by ENT8R** [comment]
Thanks, this is related to #135, during the re-import of all notes, notes that were updated since the note dump has been published were overwritten as well (because I forgot to update again all notes that were changed since then). I imported all notes and updated the notes that changed in the meantime, so this should be fixed now.

**Comment by jmizv** [comment]
Great, thank you! :pray:
