### ISSUE TITLE
Do not re-fetch notes when switching between views

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#22]
Continuing https://github.com/ENT8R/NotesReview/issues/21#issuecomment-403310652

> Yes, all notes are fetched again because the expert (list) mode is a completely different page and there is no backend where the notes could be saved temporarily...

Okay, but what about saving/"caching" them locally? Either just in the JS code (in an object/array/map/set – likely a set would be quite suitable) or some things like local storage, although the last is not really needed, as the storage does not have to be persistent between sessions.

**Comment by ENT8R** [comment]
That might be possible. I will look what I can do :grinning:

**Comment by ENT8R** [comment]
I decided to not implement the functionality to store the notes in a local/session storage because the size of the notes can easily extend 10mb which seems to be the common limit for a web storage.
And saving it in the code itself won't work, as the expert mode is a whole new page which is totally independent from the map mode.
But, what I've done in the new version is that the exact same query is used to fetch the notes when switching between views. Before it was not possible to view the exact same notes fetched with the map interface using the local/fast mode in the expert mode.
