### ISSUE TITLE
Combine list and map view

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#25]
Seeing you moved the input to the sidebar, I have one problem (although I visually generally like it):
* there is much unused space on the bottom left now

However, I see a good solution:
* Show the "list mode" there.

Having everything in one view makes it user-friendlier and would also solve https://github.com/ENT8R/NotesReview/issues/22.

Of course the views should be "merged" in a way, that interaction makes sense, i.e. e.g.:
* click on left sidebar box and it also shows you the corresponding marker on the map
* click on map marker and it shows you (the details) in the left sidebar

**Comment by ENT8R** [comment]
The white space will be definitely used once openstreetmap/openstreetmap-website#1955 is merged, because then we can also filter notes by users/id or notes created in a specific date range. Those options just need to be included in the interface of NotesReview and after that I will see whether there is still enough space to add your feature...

**Comment by ENT8R** [comment]
So, the PR was merged, I added the options and I don't think that it would be useful to condense the layout that much...
