### ISSUE TITLE
Search/filter for anonymous users

### ISSUE THREAD

**Issue by naoliv** [ENT8R/NotesReview#29]
If possible, could we have a way to search (or filter) for notes:
- [ ] created by anonymous users
- [ ] commented by anonymous
- [ ] modified (closed, reopened) by anonymous

Thanks

**Comment by ENT8R** [comment]
Yes, that's possible. I just tested it but I will have to adapt the UI a little bit maybe.

**Comment by rugk** [comment]
BTW what is the actual use case behind that? I.e., if I understood correctly, you want to filter it, so you can see all notes only by anonymous users? Is that correct?

If so, would not it equally help to see all notes _not_ by anonymous users?

**Comment by ENT8R** [comment]
> BTW what is the actual use case behind that? 

The use case would be to see all notes created by some anonymous notes spammer.

> If so, would not it equally help to see all notes not by anonymous users?

But what would be the use case of that?

**Comment by ENT8R** [comment]
With https://github.com/ENT8R/NotesReview/commit/074153b3d508d47b0942d717a7452ae61926f41c it is now possible to enter "anonymous" into the user search field. See for example https://ent8r.github.io/NotesReview/expert/?limit=100&user=anonymous&start=true
Notes which contain a comment or another action of an anonymous user are not shown yet, because the API doesn't allow this. I will try to make a PR for that.

**Comment by rugk** [comment]
Okay, so this is to find spammers… mhh… okay…

**Comment by ENT8R** [comment]
This is now resolved as there is now:
- an option to search for notes created by anonymous users.
- another option to exclude notes created by anonymous users.

What still needs to be added is a warning when both options are applied, because then obviously there will be no result at all 😄
