### ISSUE TITLE
Option to show only notes with no comments

### ISSUE THREAD

**Issue by rjw62** [ENT8R/NotesReview#40]
In terms of finding notes that no-one has considered or looked at yet, I think it would be really useful to be able to show only notes that have no comments after the initial creation. This could be used to help keen mappers triage notes, working on both old and neglected ones and new ones as they come in. This could be implemented in the user interface with a "Show only notes without comments" checkbox.

**Comment by rugk** [comment]
> working on both old and neglected ones and new ones as they come in

Hmm… I am reminded of something here: https://github.com/ENT8R/NotesReview/issues/39 (so you may have trouble seeing old and new notes at the same time… :thinking: )

**Comment by ENT8R** [comment]
I agree that this would be a helpful option. The only thing which is blocking this right now is the limitation of the OpenStreetMap API. There is currently no parameter to search for notes without comments, but I will think about enhancing the notes API with that parameter.
If this is not accepted by the maintainers of the OpenStreetMap website, then I could implement a local check to sort out notes with a comment, but that's not my preferred way of doing this because I think that also other data consumers might profit from such an option.

**Comment by ENT8R** [comment]
:tada: I finally found some time to build a [new API](https://github.com/ENT8R/notesreview-api) which allows more flexibility and I'm happy to announce that the request of this ticket is now implemented as one of the first enhancements of the new API:

![Screenshot_2021-05-24 NotesReview](https://user-images.githubusercontent.com/25306497/119410963-ec223a00-bce9-11eb-8b1a-ab5ecbde7dff.png)
