### ISSUE TITLE
multiple duplicate notes / comments when searching for user

### ISSUE THREAD

**Issue by Luzandro** [ENT8R/NotesReview#43]
Hi,

take for example this note with 7 comments, 4 of which are from me: https://www.openstreetmap.org/note/1837314

If I search for user "Luzandro" in the list view, the note gets shown 4 times and for each of them every single comment (including comments from everyone else and original note text) gets shown 4 times as well leading to 31 comments

![Opera Momentaufnahme_2019-12-07_172455_ent8r github io](https://user-images.githubusercontent.com/25511512/70377634-e0d12800-1916-11ea-81cd-69a4ae31d182.png)

**Comment by ENT8R** [comment]
Thank you for reporting this issue. I'm aware of it and the reason it has not been fixed yet is that I actually wanted to fix the issue directly in the OpenStreetMap Notes API rather than just using a local workaround, but the corresponding Pull Request has been untouched for more than two months right now... 😞
I might add a temporary workaround instead in order to fix this issue in the following days.

**Comment by rugk** [comment]
> corresponding Pull Request

Could you link that here for reference?

**Comment by ENT8R** [comment]
The pull request is actually mainly about sorting and ordering notes (i.e. that one can focus on resolving older notes), but I also added a small change that would allow to only return unique notes:
https://github.com/openstreetmap/openstreetmap-website/pull/2381

**Comment by Luzandro** [comment]
thx, fixed the main problem with duplicate notes but comments are still shown multiple times

**Comment by ENT8R** [comment]
Oh, I didn't catch that one... This is also another bug of the API. I will try to create a pull request in the main OpenStreetMap repository for that, but as it might take a little bit to be resolved, I will add another temporary workaround for this issue too.
