### ISSUE TITLE
bounding box limitation to query ist lost when switching to list view and choose a different sorting?

### ISSUE THREAD

**Issue by stephan75** [ENT8R/NotesReview#44]
Try the following:

1. In map view, pan and zoom to a quite small area of interest,
2. choose: sort by oldest,
3. start query 
4. have a result for example of only 68 notes at all, displayed on the map,
5. switch to list view of those notes,
6. there you can verify to have the same number of notes (68 in my case)
7. but the list is sorted by "latest" automatically!
8. When choosing a different list sorting ("oldest") in list view, the limitation to the formerly choosen small area is not used any more! Now I see old notes from the whole world!

Reproducible??

Is this intended?

I would like to keep geographic bounding box when altering the search/sort parameters in list view.

**Comment by ENT8R** [comment]
There are actually two issues:
-  The mode of sorting of the notes is not transferred when switching the views (and when creating a permalink to share the current query)
- The list mode does not allow the user to choose a bounding box in order to limit the results, this can only be achieved by starting the query in the map mode and switching to the list mode afterwards

I'm aware of both issues, but I just hadn't had the time to fix them...

So, as it is not possible to select a bounding box in the list mode, a first solution would be simply to pass the correct sorting mode from the map view to the list view. After that is done I might think about another option in the list view in order to specify a bounding box.

**Comment by ENT8R** [comment]
Your specific use case should be fixed with https://github.com/ENT8R/NotesReview/commit/38011b1f212ca1da2eb80d48acb5dedf864edcee
Now it is possible to pass the sorting mode as a parameter to the list or map view and via the link share menu 🎉
