### ISSUE TITLE
Date badge is not translated under Safari 

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#56]
Firefox
<img width="399" alt="Date badge Firebox" src="https://user-images.githubusercontent.com/2158081/79000295-a4c00500-7b4c-11ea-857b-d3f95b0536bf.png">

Safari
<img width="399" alt="Date badge Safari" src="https://user-images.githubusercontent.com/2158081/79000297-a5589b80-7b4c-11ea-8a66-df7c831e7786.png">

See also #54

**Comment by pyrog** [comment]
**Console**
```
[Info] [WDS] Live Reloading enabled. (vendors~main.min.js, line 1)
[Warning] [WDS] Warnings while compiling. (vendors~main.min.js, line 1)
[Warning] asset size limit: The following asset(s) exceed the recommended size limit (244 KiB). (vendors~main.min.js, line 1)
This can impact web performance.
Assets: 
  js/vendors~main.min.js (788 KiB)
[Warning] entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance. (vendors~main.min.js, line 1)
Entrypoints:
  main (836 KiB)
      js/vendors~main.min.js
      css/main.min.css
      js/main.min.js

```

**Comment by ENT8R** [comment]
You probably made this screenshots on your local instance of NotesReview after translating it, right? This is because as of now, French is not (yet 😄) a supported language of the application, so a required polyfill for [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat#Browser_compatibility) for the French language is also not loaded. But this will be fixed after I added your translation files.

**Comment by pyrog** [comment]
That's the case 👍
