### ISSUE TITLE
Query #caresteouvert_DE also shows #caresteouvert without #caresteouvert_DE

### ISSUE THREAD

**Issue by caugner** [ENT8R/NotesReview#57]
Is this intentional?

Example: https://ent8r.github.io/NotesReview/?query=%23caresteouvert_DE&closed=true

Originally we had tagged notes with `#caresteouvert #DE`, but the query `#caresteouvert #DE` showed all notes containing `caresteouvert` and the sequence `de` (e.g. in "Details").

**Comment by ENT8R** [comment]
This is certainly not intentional, but more a restriction of the OpenStreetMap Notes search API... NotesReview is just a simple front-end of the OSM Notes API. The actual search string filtering happens here:
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/api/notes_controller.rb#L277

So this is sadly nothing I could fix very fast, the only feasible solution would be either to get rid of the notes search endpoint and migrate to an own API over which I would have a little bit more control (especially of how the results are filtered), or to improve the API back-end.
I will have to think about it, but this will rather take some time. What you could do, as long as you have control over the text of the created note, would be maybe to add a locale-specific hashtag like `#bleibtoffen` or something similar?

**Comment by caugner** [comment]
Thank you for your detailed explanation for this behaviour.

I have moved this issue upstream: https://github.com/openstreetmap/openstreetmap-website/issues/2587.
