### ISSUE TITLE
Queries with higher Limit won't load

### ISSUE THREAD

**Issue by kartonage** [ENT8R/NotesReview#64]
Hej,

I have been noticing that queries with a high limit don't load at all. The loading bar appears but never finishes. 
Queries with a limit of 100-200 seem to run fine.

This seems to be for empty queries with no particular keyword since queries with keywords and a high limit run fine.
Checked on multiple browsers and PCs. 

Has there maybe been a limitation placed for queries without keyword?

**Comment by ENT8R** [comment]
> Has there maybe been a limitation placed for queries without keyword?

No, there is no limit except the API limit of 10000 notes.
The issue is not directly connected to the amount of notes that are fetched from the API, the actual issue is that notes that are created in countries which do not have an official [Regional Indicator Symbol](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol) were handled in a wrong way which led to an error.
