### ISSUE TITLE
Display any pictures

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#65]
Add a regex like this one to linkily.js ?
[(http(s)?:\/\/)?(www\.)?.*\.(jpg|jpeg|png)](https://regexr.com/5gu7o)

Example: [note 2439467](https://www.openstreetmap.org/note/2439467)

**Comment by idh** [comment]
All the links on example note and it's comments are accessible, What is wrong with the current regex? Any existing issues with it should be linked here.

**Comment by Lee-Carre** [comment]
@ArcaneDots

I believe the idea is to have URLs pointing to images be not merely rendered as a link, but to display (a thumbnail of) the image itself, when displaying the note.

**Comment by Lee-Carre** [comment]
@pyrog

> [(http(s)?://)?(www.)?.*.(jpg|jpeg|png)](//regexr.com/5gu7o)

Interesting tool (bookmarked), but sub-optimal regex. Instead:

    /^(?:https?:\/\/)?(?:www\.)?[0-9a-zA-Z%\/@\-\_\;\.\&\+\=]+\.(?:jpe?g|png|webp)/i

If you compare, using the same tool, you'll notice that the execution time is considerably less (and it'll use less memory, too).

This pattern could be refined further, in a bunch of ways, to be more specific (to well-formed URLs).

Somewhat [moot, now, due to my PR](/ENT8R/NotesReview/pull/90).

Reference site: [Regular Expressions](//www.regular-expressions.info/).

**Comment by Lee-Carre** [comment]
> This pattern could be refined further, in a bunch of ways, to be more specific (to well-formed URLs).

    (?:https?:\/\/)?(?:www\.)?(?:[\w\-]+\.)*(?:[\w\-]+)\.(?:[a-z]{2,})\.?\/(?:[\w\/]+)\.(gif|tiff?|jpe?g|[pm]ng|svg|webp)
