### ISSUE TITLE
Can't search for hashtags

### ISSUE THREAD

**Issue by westnordost** [ENT8R/NotesReview#66]
It is becoming popular to put hashtags into the comment description, for example #surveyme is used to request a survey.

However, it is not possible to search specifically for hashtags. If I enter for example "#survey" in the seach field, it ignores the hashtag and instead searches for all mentions of the word "survey". Which is not what I wanted.

**Comment by ENT8R** [comment]
Thank you for bringing this up! This behavior was already reported before (#57) and in the short term, there is probably no (easy) solution for it: 

NotesReview is actually just a very simple frontend for the OSM notes search API. It just passes the query and filters on to the API and shows the result on a map. So in terms of searching for specific character combinations, it is quite limited as the upstream API only uses a simple text query which can be found here:
https://github.com/openstreetmap/openstreetmap-website/blob/4a6b1e54a5b091badda7f149018b27981e807c49/app/controllers/api/notes_controller.rb#L275
For the future, my plan is to develop an independent API for searching notes with full flexibility, also accounting possible use cases like searching for hashtags or question marks (#15). But this will likely take some time...

**Comment by westnordost** [comment]
I see. Maybe the upstream API should be improved then

**Comment by ENT8R** [comment]
Just in case you are still interested in the outcome, I found some time to build [a new, own backend](https://github.com/ENT8R/notesreview-api) which now also allows to search for hashtags the way it should work: https://ent8r.github.io/NotesReview/?view=map&query=%22%23survey%22
It is currently needed to put the expression to search for in quotation marks (i.e. "#survey"), otherwise the search will also include results with the word "survey" but without the leading hashtag. But it is of course an improvement to the situation before.

**Comment by westnordost** [comment]
Nice!
