### ISSUE TITLE
Incrementally load notes when doing large queries

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#7]
What about loading notes after 100 notes are received and display them on the map, then do another query and load the next ones, and so on…

The advantage would be that the user can see them "popping up" on the map, i.e. the user sees there is some real progress.

Preferably, the user could also cancel the process (if they see it takes too long, i.e. the chosen limit was a bit too high) and still see all notes, which were already fetched. So one can just start the query and end it when one thinks there are enough notes, now. 😃

**Comment by ENT8R** [comment]
Isn't it inefficient to do 100 requests after each other to get 10000 notes in the end? I can't imagine that this would be faster...
And even if it would be faster, this feature won't work because everytime when this tool makes a request to the OSM API and queries only for 100 notes, the API will always return the **same** 100 notes and no new ones as the Note Search API does not support the URL parameter `...&page=2`

**Comment by rugk** [comment]
Ah uh, too bad this API...
