### ISSUE TITLE
Missing OSM tools in the map view

### ISSUE THREAD

**Issue by Crashillo** [ENT8R/NotesReview#74]
When you open the popup in the map view, the available tools (iD, JOSM, Level0...) have disappeared, only the link to OSM site still there
![imagen](https://user-images.githubusercontent.com/817526/120222628-87626480-c240-11eb-8639-2d4f80ad0b93.png)
However the list view is showing them properly
![imagen](https://user-images.githubusercontent.com/817526/120222780-cbee0000-c240-11eb-8bdf-ec9aac437cd3.png)

**Comment by ENT8R** [comment]
Thank you for your report, I added the popup in the map view just as a temporary solution before switching to a sidebar which contains all necessary information. I was just annoyed by the marker popups because the amount of content which had to fit in the (very small) popup didn't look that good IMO.
Nevertheless, I updated the view again, so now all information which was there before is now visible and usable again:

<img src="https://user-images.githubusercontent.com/25306497/120551074-eae1c300-c3f5-11eb-8a58-67c6cf6645ea.png">

**Comment by Crashillo** [comment]
Great! Since the amount of the buttons are changeable, I'd suggest to remove `btn-group btn-group-block` css classes, leaving just `note-actions`. Easy solution meanwhile:

![imagen](https://user-images.githubusercontent.com/817526/120608206-39707b00-c451-11eb-9b79-f72719128c11.png)

**Comment by ENT8R** [comment]
May I ask why you would rather like to have some more space between the buttons? Does it look too crowded at the moment, or is not maybe difficult to spot that the buttons are offering distinct actions when they are grouped together?

**Comment by Crashillo** [comment]
To keep style consistency between list and map. My goal was about displaying the buttons in a similar way in both views, but it's just a suggestion :)

**Comment by ENT8R** [comment]
Ah, I see. I will think about the styling of the buttons again 😅
