### ISSUE TITLE
Filter button doesn't filter when you hit return

### ISSUE THREAD

**Issue by peternewman** [ENT8R/NotesReview#77]
You have to hit search separately afterwards, which seems a bit unintuitive to me. Having Search and Cancel buttons in the filter dialogue might make things clearer?

**Comment by peternewman** [comment]
Actually more confusingly there is a close button which leaves the dialogue out of sync with the displayed results (for the same reason).

**Comment by ENT8R** [comment]
I have to admit, I do not really know why I implemented it this way. Maybe because the search menu was in a different place a few months ago and while redesigning the interface, I did not thought about whether this is actually simple to use.
Now you can trigger a new search by pressing the return key when the filter modal is open and of course by using the buttons (either in the modal or in the navigation bar at the top of the page). Maybe I should also rename the button in the navigation bar to something like "refresh" or "reload"...

**Comment by peternewman** [comment]
Thanks, that seems more workable.

> Maybe I should also rename the button in the navigation bar to something like "refresh" or "reload"...

Yes please, multiple times just now I've clicked search rather than filter. It also seems to do a brief search even if nothing has changed, so I guess it's doing a refresh. "Refresh" may be better as that fits quite well with browser terminology IMHO.

**Comment by ENT8R** [comment]
> > Maybe I should also rename the button in the navigation bar to something like "refresh" or "reload"...
> 
> Yes please, multiple times just now I've clicked search rather than filter. It also seems to do a brief search even if nothing has changed, so I guess it's doing a refresh. "Refresh" may be better as that fits quite well with browser terminology IMHO.

I already did this a month ago or so, but forgot to push the changes. Anyway, if there are no changes to the filters since the last search, the button now displays "Refresh" instead of "Search".
