### ISSUE TITLE
Translating notes

### ISSUE THREAD

**Issue by peternewman** [ENT8R/NotesReview#79]
A quick button to fire the note text off to translate.google or something else would be very useful, so you don't have to copy-paste it all the time. Especially for StreetComplete notes where the question is in English but the answer is in the local language.

**Comment by Lee-Carre** [comment]
Instead of Google (😒), I would much prefer [MyMemory by Translated](//mymemory.translated.net/).

It's far better fitting with a libre project (both NotesReview & OSM):
* multiple suggestions (from different sources)
* ‘multiple sources’ includes both a large body of human-transliterated texts, and algorithm-derived suggestions
* users may rate the suggestions, and contribute better ones
* there is a capable yet simple [API](//mymemory.translated.net/doc/spec.php) available (which doesn't require any key) — translations may be done on the NR site itself, instead of having to link elsewhere (as with Google)
* has all the usual features you'd expect
  * many languages
  * auto-detection of source language, which may be manually selected / overridden

**Comment by peternewman** [comment]
Awesome, yeah that looks even better!

Although the Autodetect does seem to like to favour Laotian a lot...

**Comment by Lee-Carre** [comment]
> Awesome, yeah that looks even better!

Indeed. I've seen it work very well on other sites (not that I can recall *where*, now; it's been quite some time).

> the Autodetect does seem to like to favour Laotian a lot

I've noticed similar, too. It struggles to match single words or short phrases. Longer phrases (sentence to paragraph length) have yielded better results.

Having done a little digging on their main site:
* [Automatic language identifier](//translatedlabs.com/language-identifier) [seems to be proprietary ☹]
* [ModernMT](/modernmt/modernmt) [GH repo 😀]

---

More generally, having also suggested this over at OSMCha's frontend repo, I'm (optimistically) hoping that if this service gets a hoard of contributors from OSM, then they might be more receptive to open collaboration, such as to have their auto-detection refined via patches, if they make the source available.

**Comment by ENT8R** [comment]
I decided to use [Deepl](https://www.deepl.com/translator) for this feature since (speaking from my personal experience) it's currently definitely the best translator out there.

**Comment by ENT8R** [comment]
I waited for such a long time to implement this because I always thought that notes with mixed language parts would need some separate handling (e.g. notes created by StreetComplete, OrganicMaps,...) and that it would make sense to translate only the parts written by actual users, not machines. But during my tests, translating also worked quite good for mixed language notes. And in cases where it does not work instantly, the user is still able to change the text in the translating tool to adapt it to their needs (maybe some users would also like to translate the parts that are appended automatically, but which are mostly written in English).
