### ISSUE TITLE
Cross-Origin Request Blocked listed in console on Firefox

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/NotesReview#83]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://notesreview.kongruent.xyz/api/search?query=Unable%20to%20answer%20%22What%20type%20of%20barrier%20is%20this%3F%22&limit=100&status=open&sort_by=created_at. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by matkoniecz** [comment]
It appears to work, but this should not happen.

**Comment by ENT8R** [comment]
This is definitely unexpected behaviour, thank you for reporting it.
Can you reliably reproduce it? Or does it only happen for specific queries?

**Comment by matkoniecz** [comment]
> Can you reliably reproduce it?

Sadly, no.

**Comment by ENT8R** [comment]
This seems to happen only if the server fails at creating a response in order to answer the request, though even in this case there should be an appropriate CORS header. I will investigate further...
Do you still know on which date you experienced this issue? Was it immediately before you opened an issue here or some weeks earlier?

**Comment by matkoniecz** [comment]
> Was it immediately before you opened an issue

yes

**Comment by ENT8R** [comment]
I think I finally found what triggered this behavior: In case the timeout for a request has been exceeded, the server did not add the correct CORS headers. This should be fixed now, so this should not happen again in the future
