### ISSUE TITLE
Mishandling of `view=list&apply-bbox=true` with shared URLs

### ISSUE THREAD

**Issue by Lee-Carre** [ENT8R/NotesReview#88]
Based on [the URL cited](//ent8r.github.io/NotesReview/?view=list&map=12%2F49.2%2F-2.1&apply-bbox=true) in #87, which (notably) set `view=list`.

When following that URL, while a list is indeed displayed instead of a map, the `apply-bbox=true` constraint isn't applied. The list contains entries from other nations (seemingly from a [global search](//ent8r.github.io/NotesReview/?view=list)).

This contrasts against [when `view=map` is set](//ent8r.github.io/NotesReview/?view=map&map=12%2F49.2%2F-2.1&apply-bbox=true); in that case, the result is as expected.

The only change, to elicit the failure-mode, is altering the value for `view`. However, perhaps it is related to the combination of `view=map` & `apply-bbox=true`, since the latter is what fails, rather than the `view` declaration.

Bizarrely, the URL came from the `share` function of the Web UI. For brevity, I (originally) trimmed the excess `[key]=null` pairs. I wondered if that might be a factor, so tried [an unmodified URL (copied from `share`, pasted as-is into the browser's URL bar)](//ent8r.github.io/NotesReview/?view=list&map=11%2F49.2%2F-2.1&query=null&apply-bbox=true&status=open&author=null&after=null&before=null); same failure-mode (except for `null` being treated as a literal string for `query` and `author`, but that's a different glitch). [Edit:] [minimally-corrected URL](https://ent8r.github.io/NotesReview/?view=list&map=11%2F49.2%2F-2.1&query=&apply-bbox=true&status=open&author=&after=&before=) (to yield a valid demonstration of the point relevant to this report).

Apparently there's something funky going on with the URL parser / generator code 😋.

**Comment by ENT8R** [comment]
The main problem here was that I was assuming the information about the bounding box is not needed and might be removed from the query because the current position of the map is already present in the parameters. I even left a comment in the code justifying this behavior:
https://github.com/ENT8R/NotesReview/blob/5a7911cae7b5d02f9b009e1b2d97dfb749e8c2c9/app/js/query.js#L352

This is indeed wrong, as both are actually very distinct values, especially as the values for the current zoom and position might change depending on the screen resolution. But the bounding box used for the query should always be the same when shared across devices. In addition to that, the information about the current zoom and position stored in the map parameter was actually never used to create a fitting bounding box (as already said, this would work only on devices with the same resolution, so this would have been a wrong approach either way)

**Comment by Lee-Carre** [comment]
Thankyou for the explanation & working on this report.

Unfortunately, it now seems that `apply-bbox=true` is ignored in both / either case (map or list). NotesReview now always performs a global search.

**Comment by ENT8R** [comment]
Sounds like the URL you used to test this does not have a `bbox` parameter in it?
For your example above the correct URL would be something like this now: [https://ent8r.github.io/NotesReview/?view=map&bbox=-2.3360,49.1422,-1.8965,49.2807&apply-bbox=true](https://ent8r.github.io/NotesReview/?view=map&bbox=-2.3360%2C49.1422%2C-1.8965%2C49.2807&apply-bbox=true) instead of [https://ent8r.github.io/NotesReview/?view=map&map=12/49.2/-2.1&apply-bbox=true](https://ent8r.github.io/NotesReview/?view=map&map=12%2F49.2%2F-2.1&apply-bbox=true)
Please note that the `bbox` parameter was not available before I fixed this, so you likely need to generate a new permalink in order to use a local search.

**Comment by Lee-Carre** [comment]
Oh! Whoops.

I didn't notice the more fundamental change to the query-string structure.

Your substitute URL yields the expected result.

I've got a bunch of bookmarks & links to update 😄.

Though, since the commit breaks backward compatibility (of already-shared URLs, meaning that they're not perma-URLs); was it necessary to change the required parameters?

A classic: [Cool URIs don't change](//www.w3.org/Provider/Style/URI.html). Redirects for the  win.

**Comment by ENT8R** [comment]
> was it necessary to change the required parameters?
[Edit:] ah, is this to make bbox-matching independent of display resolution?

Exactly, as the correct bounding box for the search can not be derived from a coordinate pair and a zoom level alone. To provide reproducible results, the bounding box is necessary as a (additional) parameter.

> Though, since the commit breaks backward compatibility (of already-shared URLs, meaning that they're not perma-URLs);

I just thought about it again, actually your previous URL should still work as usual, so it shouldn't be a backwards-incompatible change at all. The problem is that the bounding box value is not updating correctly, as I changed a few things during the previous change in that regard as well. This bug should be easy to fix though.

**Comment by ENT8R** [comment]
Fixed with https://github.com/ENT8R/NotesReview/commit/8a814fe27a81c1a168e5c4ac8b9ee3af188aff99. The behavior should be fully backwards-compatible now, meaning you can continue to add the `map` and `apply-bbox=true` parameter and get a local search (at least using the map view, as before)

**Comment by Lee-Carre** [comment]
> behavior should be fully backwards-compatible now

Can confirm 👍🥳.
