### ISSUE TITLE
Search also in comments

### ISSUE THREAD

**Issue by tuxayo** [ENT8R/NotesReview#93]
Interesting keywords can be in the comments. Just by chance or added willingly in a comment to make the note easier to be found. I know I did that to a note that I couldn't find when I found it. And then struggled to find it again because comments are not searched ^^"

**Comment by ENT8R** [comment]
I am sorry, but with the currently used backend this is not possible. Full-text search in a database of this size requires indexing and MongoDB does only allow a single text index per so-called collection. This means that it would be either possible to create an index for the very first comment or all comments, but not both at the same time.
I would not like to make it the default to search in all comments but instead leave the choice to the user, since I could imagine this behavior might be kind of unexpected as generally more notes would be returned which may not even contain the word they searched for in the very first comment.
