### ISSUE TITLE
Filter by User

### ISSUE THREAD

**Issue by Crashillo** [ENT8R/NotesReview#94]
When you activate the _User_ filter, the search returns only those notes whose note's **creator** matches up.
But, could be possible to add a flag to include those conversations whose user has commented also? That is, _user_ is not the creator, but a participant

**Comment by ENT8R** [comment]
Sorry for the late reply, I have been really busy the last few months.

Do you have a specific use case in mind?
I had originally decided against this because it would come along with some other problems: if the user filter would return all notes where this user commented on, should the query filter also work on all comments instead of just the first? And what about the date interval filter, does it only apply to the date the note was created, or also to the date of a particular comment that the user filter matches?

> It looks it's possible using **display_name** instead of **user** parameter. https://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API

BTW (since I implemented this part of the OpenStreetMap API): the internal implementation of both parameters is the same, the `user` parameter just searches in a different column of the database than the `display_name` parameter.
Also, the OSM API is not used anymore to query the results.

**Comment by ppete2** [comment]
I support this idea, since it would end the limit of NotesReview to just filter for Users which created a note. Often comments of Notes are as relevant as the opening post of a note. But just by "activating an optional checkbox or similar", of course the possibillity to search for useres who opened a note should be kept.

Regarding the problems mentioned by @ENT8R:
- I think date could be left as it is now: date of Note creation (you could write "creation date" in the form to make it clear to everybody)
- first or all comments: I think it just makes sense if NotesReview checks all comments of a note if a certain user commented. I would also include if this user just "reopened" or "closed" a note, since this are interactions as well.

**Comment by ENT8R** [comment]
I decided to add another option to search for users who commented on a note (author in the UI) while keeping the option to search for users who opened the note (i.e. left the first comment) (users in the UI). Separating the author of a note from the users of a note also allows to find a note that a specific user created and another specific user has commented on.
